// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DeleteRequest struct {
	Id int64 `path:"id"`
}

type DeleteResponse struct {
	Id int64 `json:"id"`
}

type GetRequest struct {
	Id int64 `path:"id"`
}

type GetResponse struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UpdateRequest struct {
	Id    int64  `path:"id"`
	Name  string `json:"name,optional"`
	Email string `json:"email,optional"`
}

type UpdateResponse struct {
	Id int64 `json:"id"`
}
